routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/','PagesController@index');
Route::get('/about','PagesController@about');
Route::get('/inspiration','PagesController@inspiration');
//Route::get('/login','PagesController@login');
//Route::get('/register','PagesController@register');


/* ++++++++++++++++++++++++ ROUTING PRODUCT +++++++++++++++++++++
 * Middleware => GUEST
 *                  URL         METHOD
 * LIST ROUTE => 1. create =>    GET
 *               2. store  =>    POST
 *               3. edit   =>    GET
 *               4. update =>    POST
 *               5. delete =>    POST/GET
 * */

Route::get('/product',               'ProductController@index');
Route::get('/product/create',        'ProductController@create');
Route::get('/product/description/{id}','ProductController@show');
Route::post('/product/store',        'ProductController@store');
Route::get('/product/edit/{id}',     'ProductController@edit');
Route::post('/product/update',       'ProductController@update');
Route::get('/product/delete/{id}',   'ProductController@destroy');




// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {

    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('cart','CartController');

    // Resources url dan method
    /*  Method          URL
     * 0. index   =>     "/"
     * 1. store   =>     "/store"
     * 2. create  =>     "/create"
     * 3. edit    =>     "/edit"
     * 4. update  =>     "/update"
     * 5. destroy =>     "/destroy"
     * */

    Route::get('users/image/{id}','UserController@image');
    Route::get('users/manage/profile/edit','ProfileController@index');
    Route::post('users/manage/profile/update','ProfileController@update');
    Route::get('users/manage/password/edit','ProfileController@changePassword');
    Route::post('users/manage/password/update','ProfileController@updatePassword');


    Route::get('list-order','CartController@showBooking');
    Route::post('list-order/upload-payment','CartController@uploadPayment');

    Route::get('invoice/{id}','InvoiceController@checkout');
    Route::post('checkout/update','InvoiceController@storeToInvoice');
});

Route::group(['middleware' => 'role:admin'], function () {
    Route::get('/dashboard', 'DashboardController@index');
    Route::get('/update-profile', 'UserController@showUpdateProfileForm');
    Route::post('/update-profile', 'UserController@updateProfile');
});

Route::group(['middleware' => 'role:seller'], function () {
    Route::get('notification/event','InvoiceController@newInvoice');
    Route::get('image/invoice/{id}','InvoiceController@getBuktiPembayaran');
    Route::post('invoice/{response}/payment','InvoiceController@responseInvoice');
    Route::get('get/review/{id}','RatingController@index');
    Route::get('review/destroy/{id}','RatingController@destroy');
});

Route::group(['middleware' => 'role:customer'], function () {
    Route::get('wishlist','WishlistController@index');
    Route::post('wishlist/store', 'WishlistController@addToWishlist');
    Route::post('wishlist/delete', 'WishlistController@removeWishlist');
    Route::post('review/store','RatingController@store');
});

Route::group(['prefix' => '/product'], function () {

    Route::group(['prefix' => '/eventorganizer'], function () {
        Route::get('/',                 'Product\EventOrganizerController@index')->name('product-eventorganizer');
        Route::get('/show/{id}',        'Product\EventOrganizerController@show')->name('product-eventorganizer-show');
        Route::get('/edit/{id}',        'Product\EventOrganizerController@edit')->name('product-eventorganizer-edit');
        Route::get('/show/{id}',        'Product\EventOrganizerController@show')->name('product-eventorganizer-show');
    });
    Route::group(['prefix' => '/decoration'], function () {
        Route::get('/',                 'Product\DecorationController@index')->name('product-decoration');
        Route::get('/show/{id}',        'Product\DecorationController@show')->name('product-decoration-show');
        Route::get('/edit/{id}',        'Product\DecorationController@edit')->name('product-decoration-edit');
        Route::get('/show/{id}',        'Product\DecorationController@show')->name('product-decoration-show');
    });
    Route::group(['prefix' => '/building'], function () {
        Route::get('/',                 'Product\BuildingController@index')->name('product-building');
        Route::get('/show/{id}',        'Product\BuildingController@show')->name('product-building-show');
        Route::get('/edit/{id}',        'Product\BuildingController@edit')->name('product-building-edit');
        Route::get('/show/{id}',        'Product\BuildingController@show')->name('product-building-show');
    });
    Route::group(['prefix' => '/merchandise'], function () {
        Route::get('/',                 'Product\MerchandiseController@index')->name('product-merchandise');
        Route::get('/show/{id}',        'Product\MerchandiseController@show')->name('product-merchandise-show');
        Route::get('/edit/{id}',        'Product\MerchandiseController@edit')->name('product-merchandise-edit');
        Route::get('/show/{id}',        'Product\MerchandiseController@show')->name('product-merchandise-show');
    });
    Route::group(['prefix' => '/food'], function () {
        Route::get('/',                 'Product\FoodController@index')->name('product-food');
        Route::get('/show/{id}',        'Product\FoodController@show')->name('product-food-show');
        Route::get('/edit/{id}',        'Product\FoodController@edit')->name('product-food-edit');
        Route::get('/show/{id}',        'Product\FoodController@show')->name('product-food-show');
    });
    Route::get('/image/{id}',       'ProductController@getImage')->name('product-image');
    Route::get('/manage',           'SellerController@manage_product')->name('product-manage');
    Route::get('/create',            'SellerController@create')->name('product.create');
    Route::post('/store',            'SellerController@store')->name('product.store');
    Route::get('/edit/{id}',            'SellerController@edit')->name('product.edit');
    Route::post('/update/{id}',            'SellerController@update')->name('product.update');
    Route::delete('/destroy/{id}',            'SellerController@destroy')->name('product.destroy');
});

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Route::post('/search', 'FilterController@filter');

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    //
    protected $fillable = [
        'product_id','customer_id'
    ];
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Cart;
use App\Invoice;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Intervention\Image\Facades\Image;

class CartController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $carts = Cart::where('customer_id',auth()->user()->id)
            ->select('products.id as product_id','products.ProductName','products.Description','products.Price','products.owner','users.name','users.contact','users.email','carts.*')
            ->leftJoin('products','products.id','=','carts.product_id')
            ->leftJoin('users','users.id','=','products.owner')
            ->get();
        $totalPrice = 0;
        foreach ($carts as $data) {
            $totalPrice = $totalPrice + $data->Price + (0.1 * $data->Price);
        }
        return view('pages.carts.index', compact('carts', 'totalPrice'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(auth()->user() == null) return abort(404); // Kalau session user tidak ada , langsung 404 Page not found

        $isExists = Cart::where('product_id', $request->get('product_id'))
            ->where('customer_id',auth()->user()->id)
            ->first();

        if($isExists) return back()->with('success','Product has Already exists in your cart');

        Cart::create([
            'product_id' => $request->get('product_id'),
            'customer_id' => auth()->user()->id,
        ]);

        $totalCart = Session::get('cart');
        Session::put('cart', $totalCart + 1); // Total cart tambah 1
        return back()->with('success', 'Success add to your cart');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id, $rowId, $product)
    {
        Cart::update($rowId, $product);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Cart::find($id)->delete();
        $cartSession = Session::get('cart');
        Session::put('cart',$cartSession-1); // Total cart sekarang dikurang 1
        return redirect()->route('cart.index')
            ->with('success','Role deleted successfully');
    }

    public function restore(){

        Cart::restore('username');
    }

    public function showBooking() {

        /* ada 2 table yang di join
         *  1. table produk
         *  2. table user
         *
         *  yang diambil dari database =>
         * 1. invoice_id
         * 2. invoice_status
         * 3. semua attribute product (productName, Price, dan lain lain)
         * 4. name dari owner product
         * */
        $list_order = Invoice::where('customer_id', auth()->user()->id)
            ->select('invoices.id as invoice_id','invoices.status','products.*','users.name')
            ->leftJoin('products','products.id','=','invoices.product_id')
            ->leftJoin('users','users.id','=','invoices.owner')
            ->get();
        return view('pages.booking.list_order', compact('list_order'));
    }
    public function uploadPayment(Request $request) {

        $invoice = Invoice::find($request->get('invoice_id'));
        $invoice->status = 'waiting for confirmation';
        $invoice->bukti_transfer = (string) Image::make($request->file('payment_receipt'))->encode('jpg', 75); // gambar di encode jadi base64 dan diubah menjadi string agar bisa dibaca oleh database
        $invoice->save();

//        Invoice::where('id',$request->get('invoice_id'))->update([
//            'status' => 'waiting for confirmation',
//            'bukti_transfer' => (string) Image::make($request->file('payment_receipt'))->encode('jpg', 75),
//        ]);
        return back()->with('success','Success upload payment receipt');
    }
}

resources/views/pages/carts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Carts</h1>
        @if(Session::get('cart') == 0)
            <div class="row justify-content-center align-items-center" style="height: 50vh;">
                <div class="col-12 text-center">
                    <h1 class="display-4">you haven't added to cart</h1>
                </div>
                <a href="{{url('/')}}" class="btn btn-outline-dark">CONTINUE SHOP</a>
            </div>
        @else
            <div class="row justify-content-center border">
                <div class="col-lg-8">
                    @foreach($carts as $data)
                        <div class="card border-0 rounded-0 mt-2">
                            <div class="card-header text-center d-flex justify-content-between ">
                                <h4>{{$data->ProductName}}</h4>
                                <div class="d-flex justify-content-between">
                                    <div class="border d-flex mr-2">
                                        <input type="hidden" name="product_id[]" value="{{$data->product_id}}">
                                        <input type="text" name="event_date[]" class="form-control-plaintext pl-2" placeholder="Select Date" value="">
                                        <button class="btn openDate"><i class="far fa-calendar-alt"></i></button>
                                    </div>

                                    <form action="{{ route('cart.destroy',$data->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-outline-danger"><i class="fas fa-trash"></i></button>
                                    </form>
                                </div>
                            </div>
                            <img src="{{asset('images/food-image-header.jpg')}}" alt="" class="card-img-top rounded-0">
                            <div class="card-body">
                                <p class="text-muted">Description</p>
                                {{$data->Description}}
                                <div class="d-flex justify-content-between border p-2">
                                    <span><i class="fas fa-user-tie"></i> {{$data->name}}</span>
                                    <span><i class="far fa-envelope"></i> {{$data->email}}</span>
                                    <span><i class="fab fa-whatsapp"></i> {{$data->contact}}</span>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
                <div class="col-lg-4">
                    <div class="card border-0 mt-2">
                        <div class="card-header text-center">
                            <h4>{{config('app.name')}} Cart</h4>
                        </div>
                        <div class="card-body">
                            <table class="table">
                                @foreach($carts as $data)
                                    <tr>
                                        <td>{{$data->ProductName}}</td>
                                        <th>Rp. {{number_format($data->Price)}}</th>
                                    </tr>
                                @endforeach
                                <tr>
                                    <td>PPN</td>
                                    <th>10%</th>
                                </tr>
                                <tr class="bg-secondary text-white">
                                    <td>Total</td>
                                    <th>Rp. {{number_format($totalPrice)}}</th>
                                </tr>
                            </table>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-outline-dark btn-block" onclick="checkout(this)">CHECKOUT</button>
                            <a href="{{url('/')}}" class="btn btn-outline-dark btn-block">CONTINUE SHOP</a>
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection
@section('script')
    <script>
        $('input[name="event_date[]"]').each(function () {
            $(this).dateRangePicker({
                autoClose: true,
                singleDate : true,
                showShortcuts: false,
                singleMonth: true
            });
        });

        $('.openDate').each(function () {
            $(this).click(function(evt) {
                evt.stopPropagation();
                var input = $(this).siblings('input');
                $(input).data('dateRangePicker').open();
            });
        });

        function checkout(e) {
            // e.preventDefault();
            var validate_date = true;
            var dates = $(':input[name="event_date[]"]').serializeArray();
            var product_id = $(':input[name="product_id[]"]').serializeArray();

            console.log(product_id);
            dates.forEach(function (key, index) {
                if(key.value === "")
                    validate_date = false;
            });

            if(!validate_date)
                alert('Please pick your date each of your event!');

            else {
                $.ajax({
                    url : '{{url('checkout/update')}}',
                    method : 'post',
                    data : {
                        _token : $('meta[name="csrf-token"]').attr('content'),
                        dates : $(':input[name="event_date[]"]').serializeArray(),
                        product : $(':input[name="product_id[]"]').serializeArray(),
                    },
                    success: function (response) {
                        alert('Success checkout, please make payment immediately, thank you!');
                        window.location.reload();
                    }
                })
            }

        }
    </script>
@endsection