routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/','PagesController@index');
Route::get('/about','PagesController@about');
Route::get('/inspiration','PagesController@inspiration');
//Route::get('/login','PagesController@login');
//Route::get('/register','PagesController@register');


/* ++++++++++++++++++++++++ ROUTING PRODUCT +++++++++++++++++++++
 * Middleware => GUEST
 *                  URL         METHOD
 * LIST ROUTE => 1. create =>    GET
 *               2. store  =>    POST
 *               3. edit   =>    GET
 *               4. update =>    POST
 *               5. delete =>    POST/GET
 * */

Route::get('/product',               'ProductController@index');
Route::get('/product/create',        'ProductController@create');
Route::get('/product/description/{id}','ProductController@show');
Route::post('/product/store',        'ProductController@store');
Route::get('/product/edit/{id}',     'ProductController@edit');
Route::post('/product/update',       'ProductController@update');
Route::get('/product/delete/{id}',   'ProductController@destroy');




// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {

    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('cart','CartController');

    // Resources url dan method
    /*  Method          URL
     * 0. index   =>     "/"
     * 1. store   =>     "/store"
     * 2. create  =>     "/create"
     * 3. edit    =>     "/edit"
     * 4. update  =>     "/update"
     * 5. destroy =>     "/destroy"
     * */

    Route::get('users/image/{id}','UserController@image');
    Route::get('users/manage/profile/edit','ProfileController@index');
    Route::post('users/manage/profile/update','ProfileController@update');
    Route::get('users/manage/password/edit','ProfileController@changePassword');
    Route::post('users/manage/password/update','ProfileController@updatePassword');


    Route::get('list-order','CartController@showBooking');
    Route::post('list-order/upload-payment','CartController@uploadPayment');

    Route::get('invoice/{id}','InvoiceController@checkout');
    Route::post('checkout/update','InvoiceController@storeToInvoice');
});

Route::group(['middleware' => 'role:admin'], function () {
    Route::get('/dashboard', 'DashboardController@index');
    Route::get('/update-profile', 'UserController@showUpdateProfileForm');
    Route::post('/update-profile', 'UserController@updateProfile');
});

Route::group(['middleware' => 'role:seller'], function () {
    Route::get('notification/event','InvoiceController@newInvoice');
    Route::get('image/invoice/{id}','InvoiceController@getBuktiPembayaran');
    Route::post('invoice/{response}/payment','InvoiceController@responseInvoice');
    Route::get('get/review/{id}','RatingController@index');
    Route::get('review/destroy/{id}','RatingController@destroy');
});

Route::group(['middleware' => 'role:customer'], function () {
    Route::get('wishlist','WishlistController@index');
    Route::post('wishlist/store', 'WishlistController@addToWishlist');
    Route::post('wishlist/delete', 'WishlistController@removeWishlist');
    Route::post('review/store','RatingController@store');
});

Route::group(['prefix' => '/product'], function () {

    Route::group(['prefix' => '/eventorganizer'], function () {
        Route::get('/',                 'Product\EventOrganizerController@index')->name('product-eventorganizer');
        Route::get('/show/{id}',        'Product\EventOrganizerController@show')->name('product-eventorganizer-show');
        Route::get('/edit/{id}',        'Product\EventOrganizerController@edit')->name('product-eventorganizer-edit');
        Route::get('/show/{id}',        'Product\EventOrganizerController@show')->name('product-eventorganizer-show');
    });
    Route::group(['prefix' => '/decoration'], function () {
        Route::get('/',                 'Product\DecorationController@index')->name('product-decoration');
        Route::get('/show/{id}',        'Product\DecorationController@show')->name('product-decoration-show');
        Route::get('/edit/{id}',        'Product\DecorationController@edit')->name('product-decoration-edit');
        Route::get('/show/{id}',        'Product\DecorationController@show')->name('product-decoration-show');
    });
    Route::group(['prefix' => '/building'], function () {
        Route::get('/',                 'Product\BuildingController@index')->name('product-building');
        Route::get('/show/{id}',        'Product\BuildingController@show')->name('product-building-show');
        Route::get('/edit/{id}',        'Product\BuildingController@edit')->name('product-building-edit');
        Route::get('/show/{id}',        'Product\BuildingController@show')->name('product-building-show');
    });
    Route::group(['prefix' => '/merchandise'], function () {
        Route::get('/',                 'Product\MerchandiseController@index')->name('product-merchandise');
        Route::get('/show/{id}',        'Product\MerchandiseController@show')->name('product-merchandise-show');
        Route::get('/edit/{id}',        'Product\MerchandiseController@edit')->name('product-merchandise-edit');
        Route::get('/show/{id}',        'Product\MerchandiseController@show')->name('product-merchandise-show');
    });
    Route::group(['prefix' => '/food'], function () {
        Route::get('/',                 'Product\FoodController@index')->name('product-food');
        Route::get('/show/{id}',        'Product\FoodController@show')->name('product-food-show');
        Route::get('/edit/{id}',        'Product\FoodController@edit')->name('product-food-edit');
        Route::get('/show/{id}',        'Product\FoodController@show')->name('product-food-show');
    });
    Route::get('/image/{id}',       'ProductController@getImage')->name('product-image');
    Route::get('/manage',           'SellerController@manage_product')->name('product-manage');
    Route::get('/create',            'SellerController@create')->name('product.create');
    Route::post('/store',            'SellerController@store')->name('product.store');
    Route::get('/edit/{id}',            'SellerController@edit')->name('product.edit');
    Route::post('/update/{id}',            'SellerController@update')->name('product.update');
    Route::delete('/destroy/{id}',            'SellerController@destroy')->name('product.destroy');
});

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Route::post('/search', 'FilterController@filter');

app/Product.php
<?php

namespace App;

use Ghanem\Rating\Traits\Ratingable as Rating;
use Illuminate\Database\Eloquent\Model;
use Intervention\Image\Facades\Image;
//use Laravel\Scout\Searchable;

class Product extends Model
{
//    use Searchable;
    /**
     * The attributes that are mass assignable.
     * @var array
     */
    use Rating;
    protected $fillable = [
        'ProductName', 'Description', 'Price', 'product_type'
    ];

    public function encodeImage($value, $quality)
    {
        return (string) Image::make($value)->encode('jpg', $quality);
    }
}

app/Http/Controllers/Product/BuildingController.php
<?php

namespace App\Http\Controllers\Product;

use App\Http\Controllers\Controller;
use App\Product;
use App\Rating;
use Illuminate\Http\Request;

class BuildingController extends Controller
{
    function __construct()
    {
//        $this->middleware('permission:product-list',['only' => ['index','show']]);
        $this->middleware('permission:product-create', ['only' => ['create','store']]);
        $this->middleware('permission:product-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:product-delete', ['only' => ['destroy']]);
    }

    /**
     * @return mixed
     */
    public function index() {
        if(auth()->guest() || auth()->user()->hasRole('customer')) {
            $product = Product::where('product_type','Building')->get();
        }else {
            $product = Product::where('product_type','Building')
                ->where('owner', auth()->user()->id)
                ->get();
        }
        return view('pages.products.rent_building.index', compact('product'));
    }

    /**
     * @param $id
     * @return mixed
     */
    public function show($id) {
        $product = Product::where('products.id',$id)
            ->select('products.*','users.name','users.contact')
            ->leftJoin('users','users.id','=','owner')
            ->first();
        $rate = null;
        $review = null;
        if (auth()->check()) {
            $rating = Rating::where('customer_id',auth()->user()->id)->where('product_id',$id)->first();
            if ($rating) {
                $rate = $rating->rating;
                $review = $rating->review;
            }else {
                $rate = 0;
                $review = null;
            }
        }

        return view('pages.products.rent_building.show', compact('product','rate','review'));
    }
}

app/Http/Controllers/Product/DecorationController.php
<?php

namespace App\Http\Controllers\Product;

use App\Http\Controllers\Controller;
use App\Product;
use App\Rating;
use Illuminate\Http\Request;

class DecorationController extends Controller
{
    function __construct()
    {
//        $this->middleware('permission:product-list',['only' => ['index','show']]);
        $this->middleware('permission:product-create', ['only' => ['create','store']]);
        $this->middleware('permission:product-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:product-delete', ['only' => ['destroy']]);
    }

    /**
     * @return mixed
     */
    public function index() {
        if(auth()->guest() || auth()->user()->hasRole('customer')) {
            $product = Product::where('product_type','Decoration')->get();
        }else {
            $product = Product::where('product_type','Decoration')
                ->where('owner', auth()->user()->id)
                ->get();
        }
        return view('pages.products.decoration.index', compact('product'));
    }

    /**
     * @param $id
     * @return mixed
     */
    public function show($id) {
        $product = Product::where('products.id',$id)
            ->select('products.*','users.name','users.contact')
            ->leftJoin('users','users.id','=','owner')
            ->first();
        $rate = null;
        $review = null;
        if (auth()->check()) {
            $rating = Rating::where('customer_id',auth()->user()->id)->where('product_id',$id)->first();
            if ($rating) {
                $rate = $rating->rating;
                $review = $rating->review;
            }else {
                $rate = 0;
                $review = null;
            }
        }
        return view('pages.products.decoration.show', compact('product','rate','review'));
    }
}

app/Http/Controllers/Product/EventOrganizerController.php
<?php

namespace App\Http\Controllers\Product;

use App\Http\Controllers\Controller;
use App\Product;
use App\Rating;
use Illuminate\Http\Request;

class EventOrganizerController extends Controller
{
    function __construct()
    {
//        $this->middleware('permission:product-list',['only' => ['index','show']]);
        $this->middleware('permission:product-create', ['only' => ['create','store']]);
        $this->middleware('permission:product-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:product-delete', ['only' => ['destroy']]);
    }

    /**
     * @return mixed
     */
    public function index() {
        if(auth()->guest() || auth()->user()->hasRole('customer')) {
            $product = Product::where('product_type','Event Organizer')->get();
        }else {
            $product = Product::where('product_type','Event Organizer')
                ->where('owner', auth()->user()->id)
                ->get();
        }
        return view('pages.products.event_organizer.index', compact('product'));
    }

    /**
     * @param $id
     * @return mixed
     */
    public function show($id) {
        $product = Product::where('products.id',$id)
            ->select('products.*','users.name','users.contact')
            ->leftJoin('users','users.id','=','owner')
            ->first();
        $rate = null;
        $review = null;
        if (auth()->check()) {
            $rating = Rating::where('customer_id',auth()->user()->id)->where('product_id',$id)->first();
            if ($rating) {
                $rate = $rating->rating;
                $review = $rating->review;
            }else {
                $rate = 0;
                $review = null;
            }
        }
        return view('pages.products.food.show', compact('product','rate','review'));
    }

}

app/Http/Controllers/Product/FoodController.php
<?php

namespace App\Http\Controllers\Product;

use App\Http\Controllers\Controller;
use App\Product;
use App\Rating;
use Illuminate\Http\Request;

class FoodController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
//        $this->middleware('permission:product-list',['only' => ['index','show']]);
        $this->middleware('permission:product-create', ['only' => ['create','store']]);
        $this->middleware('permission:product-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:product-delete', ['only' => ['destroy']]);
    }

    /**
     * @return mixed
     */
    public function index() {
        if(auth()->guest() || auth()->user()->hasRole('customer')) {
            $product = Product::where('product_type','food')->get();
        }else {
            $product = Product::where('product_type','food')
                ->where('owner', auth()->user()->id)
                ->get();
        }
        return view('pages.products.food.index', compact('product'));
    }

    /**
     * @param $id
     * @return mixed
     */
    public function show($id) {
        $product = Product::where('products.id',$id)
            ->select('products.*','users.name','users.contact')
            ->leftJoin('users','users.id','=','owner')
            ->first();
        $rate = null;
        $review = null;
        if (auth()->check()) {
            $rating = Rating::where('customer_id',auth()->user()->id)->where('product_id',$id)->first();
            if ($rating) {
                $rate = $rating->rating;
                $review = $rating->review;
            }else {
                $rate = 0;
                $review = null;
            }
        }
        return view('pages.products.food.show', compact('product','rate','review'));
    }

    /**
     * @return mixed
     */
    public function create() {
        return view('pages.products.food.create');
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function store(Request $request) {
        $validate = Validator::make($request->all(), [
            'product_name' => 'required',
            'description' => 'required',
            'price' => 'required',
        ]);
        if($validate->fails())
            return back()->withError($validate)->withInput();

        $product = new Product();
        $product->ProductName = $request->get('product_name');
        $product->Description = $request->get('description');
        $product->Price = $request->get('price');
        $product->productImage = base64_encode($request->get('product_image'));
        $product->product_type = 'food';
        $product->save();

        return redirect()->route('product-food');
    }

    /**
     * @param $id
     * @return mixed
     */
    public function edit($id) {
        $product = Product::find($id);
        return view('pages.products.food.edit', compact('product'));
    }

    public function update(Request $request, $id)
    {
        $validate = Validator::make($request->all(), [
           'product_name' => 'required',
           'description' => 'required',
           'price' => 'required',
        ]);

        if($validate->fails())
            return back()->withError($validate)->withInput();

        $product = Product::find($id);
        $product->ProductName = $request->get('product_name');
        $product->Description = $request->get('description');
        $product->Price = $request->get('price');
        $product->productImage = base64_encode($request->get('product_image'));
        $product->save();

        return redirect()->route('product-food');
    }

    /**
     * @param $id
     * @return mixed
     */
    public function destroy($id) {
        $product = Product::find($id)->delete();
        return redirect()->route('product-food');
    }
}

resources/views/pages/products/decoration/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="card rounded-0 border-0">
        <div class="card-header text-center"><h1>Decoration</h1></div>
        <img src="{{url('images/decoration-image-header.jpg')}}" class="card-img-top img-fluid" alt="">
        <div class="card-body row justify-content-center">
            @foreach($product as $data)
                <div class="col-lg-6 col-sm-12">
                    <a href="{{route('product-decoration-show',['id' => $data->id])}}" class="card nav-link text-body" style="max-width: 540px;">
                        <div class="row no-gutters">
                            <div class="col-md-4">
                                <img src="{{route('product-image',['id'=>$data->id])}}" class="card-img h-100" alt="...">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">{{$data->ProductName}}</h5>
                                    <p class="pl-0 col-12 text-truncate">{{$data->Description}}</p>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/pages/products/decoration/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        @if(session('success'))
        <!-- Modal -->
            <div class="modal fade" id="session" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-body text-center">
                            <h4>{{session('success')}}</h4>
                        </div>
                    </div>
                </div>
            </div>
        @endif
        <div class="row">
            <div class="col-lg-12">
                <h4 class="display-4 text-center">{{$product->ProductName}}</h4>
                <img src="{{route('product-image',['id'=>$product->id])}}" class="img-fluid w-100" alt="">
                <div class="row mt-4">
                    <div class="col-sm-8 border-right">
                        <p>{{$product->Description}}</p>
                        <div class="d-flex justify-content-start border p-3">
                            <div class="col-sm-4"><i class="fas fa-user-tie"></i> {{$product->name}}</div>
                            <div class="col-sm-4"><i class="fab fa-whatsapp"></i> {{$product->contact}}</div>
                        </div>
                        <p class="text-muted">If you want to ask about this event, please contact the owner of the event listed above</p>
                        @if(auth()->user() != null && auth()->user()->hasRole('customer'))
                            @include('includes.review')
                        @endif
                    </div>

                    <div class="col-sm-4">
                        <h5>Price</h5>
                        <h3>{{(is_numeric($product->Price) ? 'Rp. '.number_format($product->Price) : $product->Price)}}</h3>
                        @role('seller')
                        <a href="{{route('product-manage')}}" class="btn btn-block btn-primary">Back</a>
                        @else
                            @guest()
                                <a href="{{route('login')}}" class="btn btn-primary btn-block rounded-0"><i class="fas fa-sign-in-alt"></i> Login </a>
                            @else
                                <form action="{{route('cart.store')}}" method="POST">
                                    @csrf
                                    <input type="hidden" name="product_id" value="{{$product->id}}">
                                    <button type="button" class="btn btn-light" id="wishlistBtn" onclick="addToWishlist({{$product->id}})"><i class="far fa-heart fa-2x"></i></button>
                                    <button class="btn btn-primary btn-block rounded-0"><i class="fas fa-cart-plus"></i> Add To Cart</button>
                                </form>
                            @endguest
                        @endrole
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    @if(session('success'))
        <script>
            $('#session').modal('show');
        </script>
    @endif
@endsection